### ISSUE TITLE
Change Header Padding

### ISSUE THREAD

**Issue by steventhanna** [steventhanna/phoenix-suns-radio#6]
Change header padding-top from `100px` to `75px`

Chane this

``` css
.header {
  background-color: #391366;
  color: #fff;
  text-align: center;
  padding-top: 100px;
  padding-bottom: 75px;
}
```

to this

``` css
.header {
  background-color: #391366;
  color: #fff;
  text-align: center;
  padding-top: 75px;
  padding-bottom: 75px;
}
```
